---

- id: ansible_role_find_unused_variable
  name: Find unused variables in Ansible role
  entry: ansible_role_find_unused_variable.sh
  language: script
  description: Find unused variables in Ansible role.
