---

- id: ansible_role_find_unused_variable
  name: Find unused variables in an Ansible role
  entry: ansible_role_find_unused_variable.sh
  language: script
  description: Find unused variables in an Ansible role.

- id: ansible_role_find_empty_files
  name: Find empty files in an Ansible role
  entry: ansible_role_find_empty_files.sh
  language: script
  description: Find emtpy files in an Ansible role.

- id: ansible_role_find_empty_directories
  name: Find empty directories in an Ansible role
  entry: ansible_role_find_empty_directories.sh
  language: script
  description: Find emtpy directories in an Ansible role.

- id: ansible_role_fix_readability
  name: Fix readability in Ansible role
  entry: ansible_role_fix_readability.sh
  language: script
  description: Fix readability in Ansible role

- id: ansible_role_find_undefined_handlers
  name: Find undefined handlers
  entry: ansible_role_find_undefined_handlers.sh
  language: script
  description: Find notified handlers that are not defined.

- id: ansible_role_find_unquoted_values
  name: Find unquoted values that look like a version
  entry: ansible_role_find_unquoted_values.sh
  language: script
  description: Find version-like values that are not quoted.

- id: ansible_role_find_horizontal_when
  name: Find when statements that are not spread vertically
  entry: ansible_role_find_horizontal_when.sh
  language: script
  description: Find when statements that can be improved by vertical spreading.
